# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京东东东农场

on:
  workflow_dispatch:
  schedule:
    - cron: '20 23,4,10 * * *'
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
          npm install request
          npm install --save got
          npm install tough-cookie
      - name: '京东东东农场'
        env: 
            JD_COOKIE: ${{secrets.JD_COOKIE}}
            TG_BOT_TOKEN :  ${{secrets.TG_BOT_TOKEN}}
            TG_USER_ID :  ${{secrets.TG_USER_ID}}
            REMOTE_URL: https://raw.githubusercontent.com/lxk0301/scripts/master/jd_fruit.js
            CUSTOM_REPLACE: '[{key : /let jdNotify.+/,value : "let jdNotify = false"}]'
            MULT_CUSTOM_REPLACE: '[[{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`e3ff185ff53643308ab2b1a6afb3533e`,`323dbdbbfc824faa81b8927cd95bf975`,`732c806d465d427aab0c948e2ef8de17`,`5fe4179a7903433b898e6849409ad885`] "}],[{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`967a8e63fa2148208c1385ed34641ede`,`b8359db44d244b1f8c36e399926eb5d5`,`6d7041df49b14747b7ea240efcbe3b59`,`7b6a724115984e968ec962bf333c0d3b`]"}],[{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`b4f36c1c632746a8bcc3899a11cc19f6`,`11705719f6e34c6a95913acc5d23d640`]"}]]'
        run: |
          node 'scripts/remote/runRemoteScripts.js'
